title: Survival Protocol
description: Eternal Return 1.0 ID Squad Tournament
show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins